# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
#sudo: false

# We need at least Ubuntu 14.04 (Trusty), so no more Docker builds for now
sudo: required
dist: trusty

# Test build with both GCC and Clang (LLVM)
compiler:
  - gcc
  - clang

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "kFrbrFEPt+f2UTSoKymheDJiLOcuXqvCDeV8EqCIsQT7oMpwHxLogJio3BIAUfP9Ykm73roJPKOt5YVv6k8IGDvKuR5XOJDl4gfLM8S1L9shGuQwk8E7nC3/96IoVRnkuqsWseDbHBm/K6jV6TRIVRVyc4Dcbjdb7qBTuVF5VNE="

addons:
  apt:
    packages:
      - autopoint
  coverity_scan:
    project:
      name: "troglobit/libconfuse"
      description: "Small configuration file parser library for C"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./autogen.sh && ./configure"
    build_command:   "make check"
    branch_pattern: dev

# We don't store generated files (configure and Makefile) in GIT,
# so we must customize the default build script to run ./autogen.sh
script:
  - ./autogen.sh
  - ./configure
  - make clean
  - make check
